version: "3"

tasks:
  init:
    cmds:
      - git submodule init
      - git submodule update --init --recursive

  configure_debug:
    cmds:
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B ./build -G {{.CLI_ARGS}} -DCMAKE_BUILD_TYPE=Debug

  configure_release:
    cmds:
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B ./build -G {{.CLI_ARGS}} -DCMAKE_BUILD_TYPE=Release

  build_target_debug:
    cmds:
      - cmake --build ./build --config Debug --target {{.CLI_ARGS}}

  build_target_release:
    cmds:
      - cmake --build ./build --config Release --target {{.CLI_ARGS}}

  build_all_debug:
    cmds:
      - cmake --build ./build --config Debug --target all

  build_all_release:
    cmds:
      - cmake --build ./build --config Release --target all

  test_patterns:
    cmds:
      - cmake --build ./build --target run-tests-patterns

  clean:
    cmds:
      - cmake --build ./build --target clean
