name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'

env:
  BUILD_TYPE: Release

jobs:
  patterns:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files (::patterns/)
      id: changed-patterns
      uses: tj-actions/changed-files@v9
      with:
        files: |
          ${{github.workspace}}/include/algorithms/patterns
          ${{github.workspace}}/src/patterns
          ${{github.workspace}}/tests/patterns

    - name: Init submodule(s)
      if: steps.changed-patterns.outputs.any_changed == 'true'
      run: git submodule init && git submodule update --init --recursive

    - name: Configure CMake
      if: steps.changed-patterns.outputs.any_changed == 'true'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      if: steps.changed-patterns.outputs.any_changed == 'true'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target algorithms-patterns

    - name: Test
      if: steps.changed-patterns.outputs.any_changed == 'true'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target run-algorithms-patterns-tests

  misc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files (::misc/)
      id: changed-misc
      uses: tj-actions/changed-files@v9
      with:
        files: |
          ${{github.workspace}}/include/algorithms/misc
          ${{github.workspace}}/src/misc
          ${{github.workspace}}/tests/misc

    - name: Init submodule(s)
      if: steps.changed-misc.outputs.any_changed == 'true'
      run: git submodule init && git submodule update --init --recursive

    - name: Configure CMake
      if: steps.changed-misc.outputs.any_changed == 'true'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      if: steps.changed-misc.outputs.any_changed == 'true'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target algorithms-misc

    - name: Test
      if: steps.changed-misc.outputs.any_changed == 'true'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target run-algorithms-misc-tests
