name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'

env:
  BUILD_TYPE: Release

jobs:
  changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files (::patterns/)
      id: patterns
      uses: tj-actions/changed-files@v9
      with:
        files: |
          include/algorithms/patterns
          src/patterns
          tests/patterns

    - name: Get changed files (::misc/)
      id: misc
      uses: tj-actions/changed-files@v9
      with:
        files: |
          include/algorithms/misc
          src/misc
          tests/misc

  build:
    needs: changes

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodule(s)
      run: git submodule init && git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build (::patterns/)
      if: |
        jobs.changes.steps.patterns.outputs.any_changed == 'true' ||
        github.event_name == 'workflow_dispatch'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target algorithms-patterns

    - name: Build (::misc/)
      if: |
        jobs.changes.steps.misc.outputs.any_changed == 'true' ||
        github.event_name == 'workflow_dispatch'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target algorithms-misc

  patterns-tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      if: |
        jobs.changes.steps.patterns.outputs.any_changed == 'true' ||
        github.event_name == 'workflow_dispatch'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target run-algorithms-patterns-tests

  misc-tests:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      if: |
        jobs.changes.steps.misc.outputs.any_changed == 'true' ||
        github.event_name == 'workflow_dispatch'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target run-algorithms-misc-tests
