name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'extern/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  patterns:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodule(s)
      # Initialize the repository git submodule(s)
      run: git submodule init && git submodule update --init --recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target algorithms-patterns

    - name: Test
      # Run tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target run-tests-patterns
